spring:
  config:
    activate:
      on-profile: dev
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  redis:
    host: localhost
    port: 6379
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorizationUri: https://kauth.kakao.com/oauth/authorize
            tokenUri: https://kauth.kakao.com/oauth/token
            userInfoUri: https://kapi.kakao.com/v2/user/me
            userNameAttribute: id
          naver:
            authorizationUri: https://nid.naver.com/oauth2.0/authorize
            tokenUri: https://nid.naver.com/oauth2.0/token
            userInfoUri: https://openapi.naver.com/v1/nid/me
            userNameAttribute: response
        registration:
          google:
            clientId: 321756353789-g576uholp15jco215a06h1dgso5thp24.apps.googleusercontent.com
            clientSecret: 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
            redirect-uri: https://codetech.nworld.dev/login/oauth2/code/google
            authorization-grant-type: authorization_code
            scope:
              - email
              - profile
          naver:
            clientId: 7H590XwmpkB_tq1K_bI7
            clientSecret: E_OJywEPPm
            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            redirectUri: "http://codetech.nworld.dev/login/oauth2/code/naver"
            scope:
              - nickname
              - profile_image
              - email
            clientName: Naver
          kakao:
            clientId: 8eafbe150915e4f53b97c2cd278cb8e4
            clientSecret: 5w4KhZQilkXRuSFrtD6EwILMcWUoltZc
            clientAuthenticationMethod: post
            authorization-grant-type: authorization_code
            redirectUri: http://codetech.nworld.dev/login/oauth2/code/kakao
            scope:
              - profile_nickname
              - profile_image
            clientName: kakao
  mail:
    host: smtp.naver.com
    port: 465
    username: heakwangcodetech@naver.com
    password: Codetech!@#$11

jwt:
  secret-key: eyJhbGciOiJIUzI1NiJ9.eyJSb2xlIjoiQWRtaW4iLCJJc3N1ZXIiOiJJc3N1ZXIiLCJVc2VybmFtZSI6IkphdmFJblVzZSIsImV4cCI6MTY2ODU4NjIwMSwiaWF0IjoxNjY4NTg2MjAxfQ.9AwIFu34UEm>
  access-token-expiration-minutes: 1
  refresh-token-expiration-minutes: 10080

server:
  tomcat:
    remoteip:
      remote-ip-header: X-Forwarded-For
      protocol-header: X-Forwarded-Proto
    use-relative-redirects: true
    redirect-context-root: false
    forward-headers-strategy: native

filePath: /images/